name: publish
run-name: "Publish NPM package"
on:
  push:
    branches:
      - master
    paths:
      - src/**
      - .storybook/**
      - package.json
      - package-lock.json
      - vite.config.js

jobs:
  publish-package:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        name: "Checkout repository"

      - uses: actions/setup-node@v4
        name: "Configure Node.js"
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hfxbse'

      - run: "npm ci"
        name: "Install dependencies and build package"

      - run: "npm publish"
        name: "Publish package"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-storybook:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    needs:
      # Only publish Storybook on successful package publication
      - publish-package

    steps:
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        name: "publish storybook"
        with:
          path: storybook-static
